---
- name: Install fluentbit repo
  ansible.builtin.yum_repository:
    name: fluent-bit
    baseurl:
      - https://packages.fluentbit.io/centos/$releasever/
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://packages.fluentbit.io/fluentbit.key
    state: present
    description: 'Fluent Bit'
    repo_gpgcheck: true

- name: Install fluentbit
  ansible.builtin.dnf:
    name:
      - fluent-bit
    update_cache: true
    state: present
    enablerepo: Fluent Bit
  notify: Start fluent-bit
