---
# tasks file for fluentbit
- name: Install fluent-bit
  ansible.builtin.include_tasks:
    file: install_fluent-bit.yml
  when: not fluentbit.skip_install

- name: Copy parsers
  ansible.builtin.copy:
    src: nginx_parsers.conf
    dest: /etc/fluent-bit/nginx_parsers.conf
    owner: root
    mode: '644'
  notify: Restart fluent-bit

- name: Copy fluent-bit.conf
  ansible.builtin.template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    mode: '644'
    owner: root
  notify: Restart fluent-bit
