---
# tasks file for grafana
- name: Install grafana
  ansible.builtin.include_tasks:
    file: install_grafana.yml
  when: not grafana.skip_install

- name: Configure grafana
  ansible.builtin.include_tasks:
    file: configure_grafana.yml
