- name: Setup webservers
  hosts: webservers
  gather_facts: true
  become: true
  roles:
    - webservers
  vars_files: config.yml

- name: Setup monitoring exporters
  hosts: webservers
  gather_facts: false
  become: true
  roles:
    - monitoring_metrics
  vars_files: config.yml

- name: Setup prometheus and grafana
  hosts: monitoring
  gather_facts: false
  become: true
  roles:
    - monitoring
  vars_files: config.yml

- name: Setup fluentbit
  hosts: webservers
  gather_facts: false
  become: true
  roles:
    - logs
  vars_files: config.yml

- name: Setup es and kibana
  hosts: elk
  gather_facts: false
  become: true
  roles:
    -elk
  vars_files: config.yml

  tasks:
    - name: Install docker repo
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
        state: present