{
 "title": "NGINX Log Metrics",
 "description": "NGINX Log metrics with Prometheus based on https://www.martin-helmich.de/en/blog/monitoring-nginx.html. Based on namespace prefix 'nginx'. If different, you may need to adjust the metrics.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Total Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(status) (nginx_http_response_count_total)"
    }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "graph",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Total responses size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nginx_http_response_size_bytes)"
    }
   ]
  }
 ]
}