---
- name: Add group
  ansible.builtin.group:
    name: "kibana"
    state: present
    system: true

- name: Add user
  ansible.builtin.user:
    name: "kibana"
    group: "kibana"
    create_home: false
    shell: "/usr/sbin/nologin"
    system: true
    state: present

- name: Create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    owner: kibana
    mode: '744'
    state: directory
  loop:
    - '/etc/kibana/config'
    - '/usr/share/kibana'

- name: Create kibana container
  community.docker.docker_container:
    image: kibana:{{ kibana.version }}
    name: kibana
    env:
      ELASTICSEARCH_HOSTS: 'es.dip.lom:{{ elasticsearch.port }}'
    volumes:
      - /etc/kibana/config:/home/kibana/config
    published_ports:
      - "{{ kibana.port }}:5601"
    restart_policy: "on-failure"
    restart_retries: 3
    state: present
  notify: Start kibana

# - name: Open firewalld ports
#   ansible.posix.firewalld:
#     port: "{{ kibana.port }}/tcp"
#     state: enabled
#     immediate: true
#     permanent: true
