---
# handlers file for logs
- name: Start elasticsearch
  community.docker.docker_container:
    name: elasticsearch
    state: started

- name: Start kibana
  community.docker.docker_container:
    name: kibana
    state: started

- name: Retart elasticsearch
  community.docker.docker_container:
    name: elasticsearch
    restart: true

- name: Start kibana
  community.docker.docker_container:
    name: kibana
    restart: true
