---
- name: Create dirs
  ansible.builtin.file:
    path: '/usr/share/elasticsearch/data'
    owner: logging
    mode: '744'
    state: directory

- name: Create es container
  community.docker.docker_container:
    image: elasticsearch:{{ elasticsearch.version }}
    name: elasticsearch
    env:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      cluster.name: "netology-logging"
      node.name: "es-01"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      - memlock:-1:-1
    published_ports:
      - "{{ elasticsearch.port }}:9200"
    restart_policy: "on-failure"
    restart_retries: 3
    state: present
  notify: Start elasticsearch

# - name: Open firewalld ports
#   ansible.posix.firewalld:
#     port: "{{ elasticsearch.port }}/tcp"
#     state: enabled
#     immediate: true
#     permanent: true
