---
# tasks file for logs

- name: Add group
  ansible.builtin.group:
    name: "logging"
    state: present
    system: true

- name: Add user
  ansible.builtin.user:
    name: "logging"
    group: "logging"
    create_home: false
    shell: "/usr/sbin/nologin"
    system: true
    state: present

- name: Install Docker
  when: not kibana.skip_install and not elasticsearch.skip_install
  block:

    - name: Install docker repo
      ansible.builtin.yum_repository:
        name: docker-ce
        baseurl:
          - https://download.docker.com/linux/fedora/37/x86_64/stable
        enabled: true
        gpgcheck: true
        gpgkey:
          - https://download.docker.com/linux/fedora/gpg
        state: present
        description: 'Docker CE Stable'

    - name: Install docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
        state: present
        enablerepo: Docker CE Stable

    - name: Start docker engine
      ansible.builtin.systemd:
        service: docker
        state: started
        enabled: true

    - name: Add service acc to docker group
      ansible.builtin.user:
        user: serv_acc
        group: docker
        state: present

- name: Install elasticsearch
  ansible.builtin.include_tasks:
    file: install_elasticsearch.yml
  when: not elasticsearch.skip_install
  run_once: true
  args:
    apply:
      delegate_to: es


- name: Install kibana
  ansible.builtin.include_tasks:
    file: install_kibana.yml
  when: not kibana.skip_install
  run_once: true
  args:
    apply:
      delegate_to: kibana

# - name: Install fluent-bit repo

# - name: Get fluent-bit
#   notify restart and enable service

# - name: Open firewalld ports
#   ansible.posix.firewalld:
#     port: "{{ fluent-bit.port }}/tcp"
#     state: enabled
#     immediate: true
#     permanent: true

# Стоит разбить на два плейбука - с установкой и конфигурацией
