---
# handlers file for fluentbit

- name: Start fluentbit
  ansible.builtin.systemd:
    service: 'fluent-bit'
    state: started
    enabled: true

- name: Restart fluentbit
  ansible.builtin.systemd:
    service: 'fluent-bit'
    state: restarted
    enabled: true
