---
# tasks file for monitoring

- name: Install prometheus
  ansible.builtin.include_tasks:
    file: install_prometheus.yml
  when: not prometheus.skip_install

- name: Configure prometheus
  ansible.builtin.include_tasks:
    file: configure_prometheus.yml
