---
# handlers file for monitoring
- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Prometheus restart
  ansible.builtin.systemd:
    service: prometheus
    enabled: true
    state: restarted
